FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

COPY ../generate_keys.py /generate_keys.py

RUN cd / && python3 generate_keys.py || true

EXPOSE 8002