"""Remove user unigue in Notes db model

Revision ID: b6fc6735b713
Revises: da20a5438b35
Create Date: 2026-01-24 07:08:05.195275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6fc6735b713"
down_revision: Union[str, Sequence[str], None] = "da20a5438b35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_notes_orms_user"), "notes_orms", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_notes_orms_user"),
        "notes_orms",
        ["user"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
