"""Create media urls in Notes model

Revision ID: 629129eea129
Revises: d83d3f99e60f
Create Date: 2026-01-16 00:11:41.713830

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "629129eea129"
down_revision: Union[str, Sequence[str], None] = "d83d3f99e60f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notes_orms",
        sa.Column("video_urls", sa.ARRAY(sa.String()), nullable=False),
    )
    op.add_column(
        "notes_orms",
        sa.Column("image_urls", sa.ARRAY(sa.String()), nullable=False),
    )
    op.add_column(
        "notes_orms",
        sa.Column("audio_urls", sa.ARRAY(sa.String()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notes_orms", "audio_urls")
    op.drop_column("notes_orms", "image_urls")
    op.drop_column("notes_orms", "video_urls")
    # ### end Alembic commands ###
