"""Add user to Notes

Revision ID: da20a5438b35
Revises: 629129eea129
Create Date: 2026-01-21 20:52:59.785143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da20a5438b35"
down_revision: Union[str, Sequence[str], None] = "629129eea129"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes_orms", sa.Column("user", sa.String(), nullable=False))
    op.create_unique_constraint(
        op.f("uq_notes_orms_user"), "notes_orms", ["user"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_notes_orms_user"), "notes_orms", type_="unique"
    )
    op.drop_column("notes_orms", "user")
    # ### end Alembic commands ###
