"""Add media files tables

Revision ID: a16c32e16d67
Revises: 010b19d0c2ca
Create Date: 2026-02-19 00:50:17.829155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utc

# revision identifiers, used by Alembic.
revision: str = "a16c32e16d67"
down_revision: Union[str, Sequence[str], None] = "010b19d0c2ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_files_orms",
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("s3_url", sa.String(length=512), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("uploaded_at_s3", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["notes_orms.id"],
            name=op.f("fk_audio_files_orms_note_id_notes_orms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio_files_orms")),
        sa.UniqueConstraint("s3_url", name=op.f("uq_audio_files_orms_s3_url")),
    )
    op.create_index(
        op.f("ix_audio_files_orms_uuid"),
        "audio_files_orms",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "image_files_orms",
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("s3_url", sa.String(length=512), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("uploaded_at_s3", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["notes_orms.id"],
            name=op.f("fk_image_files_orms_note_id_notes_orms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_files_orms")),
        sa.UniqueConstraint("s3_url", name=op.f("uq_image_files_orms_s3_url")),
    )
    op.create_index(
        op.f("ix_image_files_orms_uuid"),
        "image_files_orms",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "video_files_orms",
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("s3_url", sa.String(length=512), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("uploaded_at_s3", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["notes_orms.id"],
            name=op.f("fk_video_files_orms_note_id_notes_orms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_files_orms")),
        sa.UniqueConstraint("s3_url", name=op.f("uq_video_files_orms_s3_url")),
    )
    op.create_index(
        op.f("ix_video_files_orms_uuid"),
        "video_files_orms",
        ["uuid"],
        unique=True,
    )
    op.drop_column("notes_orms", "video_uuid")
    op.drop_column("notes_orms", "image_uuid")
    op.drop_column("notes_orms", "audio_uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notes_orms",
        sa.Column(
            "audio_uuid",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "notes_orms",
        sa.Column(
            "image_uuid",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "notes_orms",
        sa.Column(
            "video_uuid",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(
        op.f("ix_video_files_orms_uuid"), table_name="video_files_orms"
    )
    op.drop_table("video_files_orms")
    op.drop_index(
        op.f("ix_image_files_orms_uuid"), table_name="image_files_orms"
    )
    op.drop_table("image_files_orms")
    op.drop_index(
        op.f("ix_audio_files_orms_uuid"), table_name="audio_files_orms"
    )
    op.drop_table("audio_files_orms")
    # ### end Alembic commands ###
