"""Add category of file in files metadata table

Revision ID: db828f969386
Revises: 20fcdd5a0c5d
Create Date: 2026-02-18 22:27:29.387120

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db828f969386"
down_revision: Union[str, Sequence[str], None] = "20fcdd5a0c5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column(
        "files_metadata_orms",
        sa.Column("category", sa.String(length=100), nullable=True),
    )
    
    # Set default value for existing rows
    op.execute("UPDATE files_metadata_orms SET category = 'unknown' WHERE category IS NULL")
    
    # Make column not nullable
    op.alter_column("files_metadata_orms", "category", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files_metadata_orms", "category")
    # ### end Alembic commands ###
