"""File_id: UUID -> str typing

Revision ID: 0519426be747
Revises: 270901670676
Create Date: 2026-03-01 22:29:50.683221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0519426be747"
down_revision: Union[str, Sequence[str], None] = "270901670676"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files_metadata_orms",
        "uuid",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "files_metadata_orms",
        "s3_url",
        existing_type=sa.VARCHAR(length=512),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files_metadata_orms",
        "s3_url",
        existing_type=sa.VARCHAR(length=512),
        nullable=False,
    )
    op.alter_column(
        "files_metadata_orms",
        "uuid",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
