"""convert file_id to UUID in files metadata

Revision ID: 3f9a81100826
Revises: cbf214a3b18c
Create Date: 2026-03-09 12:38:05.105473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3f9a81100826"
down_revision: Union[str, Sequence[str], None] = "cbf214a3b18c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Очистка невалидных UUID перед конвертацией типа
    op.execute(
        """
        DELETE FROM files_metadata_orms 
        WHERE file_id !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files_metadata_orms",
        "file_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Uuid(),
        existing_nullable=False,
        postgresql_using="file_id::uuid",
    )
    op.alter_column(
        "files_outbox_orms",
        "body",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files_outbox_orms",
        "body",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "files_metadata_orms",
        "file_id",
        existing_type=sa.Uuid(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using="file_id::varchar",
    )
    # ### end Alembic commands ###
