"""Rename file UUID to file_id

Revision ID: cbf214a3b18c
Revises: 0519426be747
Create Date: 2026-03-01 22:33:12.966282

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbf214a3b18c"
down_revision: Union[str, Sequence[str], None] = "0519426be747"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files_metadata_orms",
        sa.Column("file_id", sa.String(), nullable=True),
    )
    op.execute("UPDATE files_metadata_orms SET file_id = uuid::text")
    op.alter_column(
        "files_metadata_orms",
        "file_id",
        nullable=False,
    )
    op.drop_index(op.f("ix_files_metadata_orms_uuid"), table_name="files_metadata_orms")
    op.create_index(
        op.f("ix_files_metadata_orms_file_id"),
        "files_metadata_orms",
        ["file_id"],
        unique=True,
    )
    op.drop_column("files_metadata_orms", "uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files_metadata_orms",
        sa.Column("uuid", sa.String(), autoincrement=False, nullable=False),
    )
    op.execute("UPDATE files_metadata_orms SET uuid = file_id::text")
    op.drop_index(
        op.f("ix_files_metadata_orms_file_id"),
        table_name="files_metadata_orms",
    )
    op.create_index(
        op.f("ix_files_metadata_orms_uuid"),
        "files_metadata_orms",
        ["uuid"],
        unique=True,
    )
    op.drop_column("files_metadata_orms", "file_id")
    # ### end Alembic commands ###
